common: &common
  adapter: mysql2
  username: root
  encoding: utf8
  host: localhost

development:
  database: wagn_cruise_development
  <<: *common

test:
  database: wagn_cruise_test
  <<: *common

cucumber:
  database: wagn_cruise_test
  <<: *common

